apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-njef
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jcgi-tenant/rhtap-demo-app/hacbs-test-project-njef@sha256:d21e757a3e55e270e9a17dbeab3884037847b3970dc530c65df05ad4c965a00d
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
