apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-njef
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jcgi-tenant/rhtap-demo-app/hacbs-test-project-njef@sha256:37c16d72f6342e42cb068d50c24c5c0c908bc86f6cfa0f0bde7319237fcc8ea0
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
