apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-njef
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-njef
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-njef
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-njef
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-njef
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jcgi-tenant/rhtap-demo-app/hacbs-test-project-njef@sha256:d21e757a3e55e270e9a17dbeab3884037847b3970dc530c65df05ad4c965a00d
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
